Remove s from FunctionalTestsData and BaselineTestsData
microsoft/binskim pull request #597
Opened 2022-03-05 01:46 UTC by shaopeng-gh

# Description:

The **ONLY** change in this PR is to: 
Remove s from FunctionalTestsData and BaselineTestsData

2022-03-05 02:03 UTC, shaopeng-gh commented on docs/FunctionalTestBuildScripts.md
>  This file records scripts used to compile the test files, in alphabetical order.
>This [](http://example.com/codeflow?start=0&length=4)

Both CodeFlow and GitHub does not show all files for me... may be a max number of files limit?

this is the commit:

[https://github.com/microsoft/binskim/commit/547e02f2a9e6dd819400a3d7a49d7438bf0fc614](https://github.com/microsoft/binskim/commit/547e02f2a9e6dd819400a3d7a49d7438bf0fc614)

if you scroll to last file it is
"src/Test.UnitTests.BinaryParsers/PEBinary/PETests.cs"
but not showing here for me.

2022-03-06 22:26 UTC, michaelcfanning requested changes
:clock1:

2022-03-06 22:27 UTC, michaelcfanning commented
You don't need to make this change. The note you received the other day was to update the name of a directory named 'TestsData' to 'TestData', following other directories in the repo. Please note there is a directory named 'TestsData', I think in the BinaryParsers directory that needs to be fixed.

2022-03-06 22:40 UTC, shaopeng-gh commented
got it, let me also change the "TestsData" folder in the "Test.UnitTests.BinaryParsers"

2022-03-06 22:43 UTC, michaelcfanning commented
I changed my mind and merged this PR. :) Although we didn't ask for the change, I think the consistency is good. So just start a different change for the 'TestsData' problem :)

---
In reply to: [1060053412](https://github.com/microsoft/binskim/pull/597#issuecomment-1060053412) [](http://example.com/codeflow?ancestors=1060053412,1060053412)

2022-03-06 22:46 UTC, shaopeng-gh commented
sounds good, will do that.

---
In reply to: [1060053808](https://github.com/microsoft/binskim/pull/597#issuecomment-1060053808) [](http://example.com/codeflow?ancestors=1060053808,1060053412)

2022-03-06 23:14 UTC, shaopeng-gh commented
sorry this change itself is incomplete, there are a few files not in solution but in the repo, let me fix that first.

---
In reply to: [1060054238](https://github.com/microsoft/binskim/pull/597#issuecomment-1060054238) [](http://example.com/codeflow?ancestors=1060054238,1060053412)

2022-03-06 23:30 UTC, shaopeng-gh commented
1. This is ready, missed a file RuleContributions.md under doc.
2. if we want to check in this pr, I will also create a PR for **SDK**, because this is in that repo as well:

![image](https://user-images.githubusercontent.com/81775155/156946928-021ec27d-65df-409b-bef1-475f9429077b.png)

2022-03-06 23:33 UTC, shaopeng-gh commented
Oh btw auto merge will not trigger unless status is changed from "Changes requested" to "Approved".

2022-03-06 23:47 UTC, michaelcfanning approved these changes
:shipit:

2022-03-06 23:47 UTC, merged